"""LLM abstraction layer - supports OpenRouter with pluggable providers."""
import json
import logging
from typing import Optional, Dict, Any

import httpx

from core.config import settings

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "⚠️ DISCLAIMER: This analysis is generated by AI for informational purposes only. "
    "It does not constitute financial advice, investment recommendations, or any guarantee "
    "of outcomes. Always conduct your own research and consult a qualified financial advisor "
    "before making investment decisions. Past performance does not predict future results."
)

SYSTEM_PROMPT = """You are CIP Research Analyst, an AI assistant for the Crypto Intelligence Platform.

Your ONLY permitted tasks:
1. Summarize market data and metrics objectively
2. Explain observed trends based on provided data
3. Identify potential risks visible in the data
4. Generate structured research notes

You MUST NEVER:
- Predict prices or future market movements
- Recommend buying, selling, or holding any asset
- Express certainty about investment outcomes
- Claim that any investment is safe or guaranteed

Always use hedged, analytical language: "the data suggests", "metrics indicate", "one risk factor may be", etc.
Always include the disclaimer at the end of your response."""


class LLMProvider:
    """Base LLM provider interface."""

    async def complete(self, prompt: str, system: str = SYSTEM_PROMPT, max_tokens: int = 1500) -> str:
        raise NotImplementedError


class OpenRouterProvider(LLMProvider):
    """OpenRouter LLM provider."""

    def __init__(self, model: str = None):
        self.model = model or settings.DEFAULT_LLM_MODEL
        self.base_url = settings.OPENROUTER_BASE_URL
        self.api_key = settings.OPENROUTER_API_KEY
        self.client = httpx.AsyncClient(timeout=60.0)

    async def complete(self, prompt: str, system: str = SYSTEM_PROMPT, max_tokens: int = 1500) -> str:
        if not self.api_key:
            logger.warning("No OpenRouter API key configured; returning placeholder.")
            return self._placeholder_response(prompt)

        try:
            resp = await self.client.post(
                f"{self.base_url}/chat/completions",
                headers={
                    "Authorization": f"Bearer {self.api_key}",
                    "HTTP-Referer": "https://cip.app",
                    "X-Title": "Crypto Intelligence Platform",
                    "Content-Type": "application/json",
                },
                json={
                    "model": self.model,
                    "max_tokens": max_tokens,
                    "messages": [
                        {"role": "system", "content": system},
                        {"role": "user", "content": prompt},
                    ],
                },
            )
            resp.raise_for_status()
            data = resp.json()
            content = data["choices"][0]["message"]["content"]
            return content
        except Exception as e:
            logger.error(f"OpenRouter error: {e}")
            return self._placeholder_response(prompt)

    def _placeholder_response(self, prompt: str) -> str:
        return (
            "AI analysis is temporarily unavailable (API key not configured). "
            "Please configure OPENROUTER_API_KEY to enable AI-powered research summaries.\n\n"
            + DISCLAIMER
        )

    async def close(self):
        await self.client.aclose()


class LLMService:
    """High-level LLM service for CIP research tasks."""

    def __init__(self, provider: LLMProvider = None):
        self.provider = provider or OpenRouterProvider()

    async def generate_research_report(self, asset_data: Dict[str, Any]) -> Dict[str, Any]:
        """Generate a structured research report for an asset."""
        prompt = f"""Analyze this crypto asset and return a JSON object with EXACTLY these keys:
{{
  "executive_summary": "2-3 sentence overview of current market position",
  "key_opportunities": ["opportunity 1", "opportunity 2", "opportunity 3"],
  "key_risks": ["risk 1", "risk 2", "risk 3"],
  "ecosystem_health": "1-2 sentence assessment of protocol/ecosystem metrics",
  "research_notes": "additional analytical observations"
}}

Asset Data:
{json.dumps(asset_data, indent=2, default=str)}

Return ONLY valid JSON. No markdown, no preamble. The analysis must be based solely on the provided data.
Remember: do not predict prices or recommend actions."""

        response = await self.provider.complete(prompt, max_tokens=1200)

        try:
            # Strip markdown code fences if present
            clean = response.strip()
            if clean.startswith("```"):
                clean = clean.split("```")[1]
                if clean.startswith("json"):
                    clean = clean[4:]
            parsed = json.loads(clean.strip())
            parsed["disclaimer"] = DISCLAIMER
            return parsed
        except Exception:
            return {
                "executive_summary": response[:500] if response else "Analysis unavailable.",
                "key_opportunities": [],
                "key_risks": [],
                "ecosystem_health": "Data insufficient for ecosystem assessment.",
                "research_notes": response,
                "disclaimer": DISCLAIMER,
            }

    async def generate_comparison_analysis(self, asset_a: Dict, asset_b: Dict) -> str:
        """Generate a comparative analysis between two assets."""
        prompt = f"""Compare these two crypto assets based on their metrics. 
Provide a balanced, data-driven comparison covering:
1. Market cap and valuation differences
2. TVL and protocol health (if applicable)
3. Liquidity and volume profile differences
4. Risk profile differences

Asset A: {json.dumps(asset_a, indent=2, default=str)}
Asset B: {json.dumps(asset_b, indent=2, default=str)}

Keep the response to 3-4 paragraphs. Base ALL observations on the provided data only.
Do NOT recommend which to buy/sell/hold. End with the standard disclaimer."""

        return await self.provider.complete(prompt, max_tokens=800)

    async def generate_risk_explanation(self, asset_name: str, metrics: Dict[str, Any]) -> Dict[str, str]:
        """Generate human-readable risk explanations."""
        prompt = f"""Based on these metrics for {asset_name}, provide brief risk explanations (1-2 sentences each).
Return ONLY valid JSON:
{{
  "liquidity_explanation": "explanation of liquidity risk score",
  "concentration_explanation": "explanation of concentration risk score",
  "ecosystem_explanation": "explanation of ecosystem risk score",
  "overall_explanation": "overall risk summary"
}}

Metrics: {json.dumps(metrics, indent=2, default=str)}
Base explanations on the data. Do not predict or recommend."""

        response = await self.provider.complete(prompt, max_tokens=600)
        try:
            clean = response.strip().lstrip("```json").lstrip("```").rstrip("```")
            return json.loads(clean.strip())
        except Exception:
            return {
                "liquidity_explanation": "Risk score computed from available liquidity data.",
                "concentration_explanation": "Risk score based on market concentration metrics.",
                "ecosystem_explanation": "Risk score derived from protocol and ecosystem metrics.",
                "overall_explanation": "Composite risk score across all dimensions.",
            }


# Singleton
llm_service = LLMService()
